name: Cobol

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/cobol.yml
      - cobol/**
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/cobol.yml
      - cobol/**

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cobol

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Java
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "temurin"

      - name: Configure Cobol
        run: apt-get install -y gnucobol && cobc --version
