name: Go

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/go.yml
      - go/**
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/go.yml
      - go/**

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: go

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go/go.mod'
          cache: false

      - name: Test
        run: go test -test.v
