name: Go

on:
  push:
    branches: [ "main" ]
    paths:
      - go/**
  pull_request:
    branches: [ "main" ]
    paths:
      - go/**

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: go

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure Go
      uses: actions/setup-go@v4
      with:
        go-version-file: 'go/go.mod'
        cache: false

    - name: Test
      run: go test -test.v
