name: JavaScript

on:
  push:
    branches: [ "main" ]
    paths:
      - javascript/**
  pull_request:
    branches: [ "main" ]
    paths:
      - javascript/**

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Test
      run: npm test
