name: JavaScript

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/javascript.yml
      - javascript/**
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/javascript.yml
      - javascript/**

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: javascript

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure Node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: javascript/package-lock.json

      - name: Install
        run: npm install

      - name: Test
        run: npm test
