name: Kotlin

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/kotlin.yml
      - kotlin/**
  pull_request:
    branches: [ "main" ]
    paths:
      - .github/workflows/kotlin.yml
      - kotlin/**

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Gradle cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-kotlin-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-kotlin        

    - name: Build
      uses: gradle/gradle-build-action@8baac4c8ef753599f92eeb509c246d09d6250fa6
      with:
        arguments: build
        build-root-directory: kotlin
