name: Rust

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/rust.yml
      - rust/**
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/rust.yml
      - rust/**

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: rust

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: cargo test

      - name: Build
        run: cargo build
