name: Swift

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/swift.yml
      - swift/**
  pull_request:
    branches: ["main"]
    paths:
      - .github/workflows/swift.yml
      - swift/**

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-12

    defaults:
      run:
        working-directory: swift

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: swift test

      - name: Build
        run: swift build
